runtime: python312

entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

env_variables:
  NEON_DSN: "postgresql://dbuser:Noway2025%40%25@34.18.116.61:5432/neondb_clone_20250711_163036"
